### PR TITLE
Provide kwin 5.18.5-r1 over r0

### PR DESCRIPTION
**Pull request by yoqto**
Works for me

### CODE REVIEW

**Comment by tildearrow** [comment]
Hmm... I suggest you to apply those patches on kwin-lowlatency, as it will benefit every distro instead of just Gentoo (and prevents the release numbers from getting out of sync).

**Comment by agates** [comment]
Are these from the main Gentoo repo?  What's the context here?

**Comment by yoqto** [comment]
@tildearrow: Fair point. This won't fix it for Gentoo, though, as Gentoo already marched ahead and its package manager picks the one with the highest version number. It may also complicate your merging efforts for the next official release of kwin (if those lines were to be updated again upstream). At any rate, see tildearrow/kwin-lowlatency#79 for your consideration.

@agates:
Yes, they're from the Gentoo repo, sorry for the confusion. Please see the following commits from upstream:
- https://github.com/gentoo/gentoo/commits/7106686b19130dfbc4f42064feb0cefcbcc19aff/kde-plasma/kwin -->
  - gentoo/gentoo@fc03ea97850597e3d1f70a5189080af4078ee272
  - gentoo/gentoo@4410ebee118ca372a9db22dde9cfedcca6299bde
  - gentoo/gentoo@7106686b19130dfbc4f42064feb0cefcbcc19aff

Hope this clarifies things a bit.

**Comment by agates** [comment]
@yoqto yup, sorry for just getting to this.  Day job has taken all of my time :/.

I'm going to accept this for now to follow the Gentoo upstream.

**Pull request merged**
