### PR TITLE
Provide kwin 5.19.5

### PR DESCRIPTION
**Pull request by yoqto**
Tentative ebuild and PR for those that can't wait. Based on quick and straight-forward local merge of kwin-lowlatency's `master` with upstream's 5.19.5 tag

### CODE REVIEW

**Comment by tildearrow** [comment]
Are you sure? This will desync the version number when I release 5.19.5...

The reason why I haven't done that yet is due to [this bug](https://github.com/tildearrow/kwin-lowlatency/issues/95).

**Comment by yoqto** [comment]
Weird, but thanks for the heads-up! I don't have any such issue. When I lock my screens, I have a load of essentially 0, no pegged core, nothing. The "noisiest" application is `htop` with 2% on one core from my SSH connection via my phone.

**Review by agates — APPROVED** [review]

**Comment by tildearrow** [comment]
No! You will break the versioning scheme when 5.19.5 comes out...

**Comment by agates** [comment]
That has happened in the past without issue, has it not?  We can keep track of revisions here.

**Comment by agates** [comment]
I can't reproduce the issue either... since it's `~amd64` and not the main Gentoo repo I think we can merge it.  Worst case, a user reverts to 5.19.4 or builds with `USE=-lowlatency`.

**Comment by agates** [comment]
No, it's not urgent.  I can hold off on this.  Just means Gentoo users don't have lowlatency enabled if they have updated to 5.19.5.  It's trivial for them to pull this repository and checkout this branch.

**Comment by tildearrow** [comment]
Success. 5.19.5 is now out.

**Comment by agates** [comment]
You really didn't have to rush anything.  We could have dealt with the revision differences, it happens all the the time in Gentoo.

**Comment by agates** [comment]
Patch is exactly the same as what I can tell from the official upstream release.  Merging.

**Pull request merged**
