### PR TITLE
Update KWin ebuild from 5.20.5-r1 to 5.21.5-r1

### PR DESCRIPTION
**Pull request by ran-dall**
Just bringing the ebuild up-to-date with Gentoo's upstream. 

Might need further testing...but first try, seems okay...

### CODE REVIEW

**Comment by ran-dall** [comment]
My bad, the current upsteam is set to 5.21.5-r1, not 5.22.5-r1. 
I've updated the PR to reflect the current version on Gentoo's upstream.

**Comment by agates** [comment]
@ran-dall I'm OK with pulling this, but my understanding is the `lowlatency` patches are no longer necessary with recent versions of KWin.  Normally I follow upstream `kwin-lowlatency` but that project has not seen a release in quite some time due to those qute understandable reasons.

Comments here:
https://github.com/tildearrow/kwin-lowlatency#is-kwin-lowlatency-reaching-its-final-days

I've also more or less been running wayland exclusively and wont be able to test this myself due to other time constraints, just FYI

**Comment by ran-dall** [comment]
Hey @agates, yup, you're is not wrong, however, they're still not entirely useless. I am on NVIDIA, myself, and there are still a few little things I believe that patches help with. At least in my case, which I'm (mostly) using the native NVIDIA compositor pipeline (which means that KWin's compositing is turned off) (and isn't 100% there yet with Wayland, at least from my testing).

**I'm currently going over all the code myself and testing it, and I'll keep updating this PR with the changes. I'll ping you when I think it's ready. But yes, all-in-all, alot of these patches seem to ready for deletation**

But, yeah, because of NVIDIA's problems with Wayland, I can't make the move to Wayland 100% (it's like 80% of the way there) but someday soon I hope.

**Comment by ran-dall** [comment]
@agates You're gonna laugh but I kinda just realized that this the Gentoo Overlay. Therefore, I figuire that I might as well send my patches changes upstream and then open a new PR later, if my changes get accepted.

That said, I may open an NVIDIA branch later on too, cause I see that upstream has an NVIDIA branch...

Sorry for the bother!

**Comment by ran-dall** [comment]
@agates JK. I kid. I kid. 

Actually, I found a [thread](https://github.com/tildearrow/kwin-lowlatency/issues/106) that had everything I needed, so I figuired I just put it together for everyone...since I already had most of it put together from before. FTW so that you know, this is the first ebuild I've done since I don't know when? I think the EAPI must have been at like 3 or 4 or something. Anyways, I know the patch isn't really about "low latency" but...still...it makes a difference.

Also, I got rid the no-op patches. One was marked fixed in 5.21, and [the other was too](https://bugs.kde.org/show_bug.cgi?id=427840#c13). I didn't know if the gstream.patch still applied, I kept it and compiled everything seem fine.

Anyways, pardon the mess, I don't `git` setup on this computer yet, so I had to do it all on GitHub's web interface.

**Comment by ran-dall** [comment]
BTW for anyone using NVIDIA, https://github.com/tildearrow/kwin-lowlatency/issues/106#issuecomment-855309633, MAGIC! ⚡

**Comment by agates** [comment]
> Anyways, I know the patch isn't really about "low latency" but...still...it makes a difference.

Might be simpler for you to maintain a separate fork with an "nvidia" flag or something just to avoid the confusion.  Some people may have kept this overlay installed and don't have an NVIDIA card -- I don't want to cause issues for them.

**Comment by ran-dall** [comment]
Sorry for confusing you, this has nothing to do with NVIDIA. I was simply making a comment that turning off "Allow Flipping" suggest seems to do some good now with the framerate.

Anyways, all this patch does is add the fullscreen unredirection features, as they are the only part of the patch set that's hasn't been addressed yet by upstream. It's the same patch that was suggested on the thread, just merged for ease of use. Everything else the patch set otherwise addressed has already (for the most part) been taken care of. However, as I said before, I'm not sure about the gstream.path, but I know the other two where taken care of by 5.21.

...and yes, I was thinking that as well. However this seems to good enough for now, but maybe in the future, it would be better to keep a seperate fork or at least a seperate branch.

Otherwise, I think this is goo to merge.

**Pull request merged**
